# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4185e36678b3bad6d8b5cebddbd8e3be53e995c8305a1bb69b2d530fd45014c070daae5dd742a6ad932195739f25527ba087bad8835048a4cb0d0e68734a3b40

test:
  secret_key_base: 1547fef74347d217bab3f173c58931474c21a3c0a0f4aec07783a763229c21a53ea60bcb0984dbefe1cacd5756ef6a41ff1285b864e3040409472bc0b1efec63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
